#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H

#define BFG_BST_MIN 0
#define BFG_BST_MAX 1530

#define BFG_MOVE_TYPE_NONE 0xFF

#define TRAINER_CLASS_DEFAULT // Unhandled Trainer Class / Factory Rental Picks

enum {
    BFG_SPREAD_TYPE_OFFENSIVE,
    BFG_SPREAD_TYPE_DEFENSIVE,
};

enum {
    BFG_SPREAD_CATEGORY_PHYSICAL,
    BFG_SPREAD_CATEGORY_SPECIAL, 
    BFG_SPREAD_CATEGORY_MIXED,
};

enum {
    BFG_TEAM_GENERATOR_DEFAULT,
    BFG_TEAM_GENERATOR_RANDOM,
    BFG_TEAM_GENERATOR_FILTERED,
    BFG_TEAM_GENERATOR_FILTERED_ATTACKS_ONLY,
    BFG_TEAM_GENERATOR_FILTERED_RANKING,
    BFG_TEAM_GENERATOR_FILTERED_RANKING_ATTACKS_ONLY,
    BFG_TEAM_GENERATOR_VARIABLE,
};

enum {
    BFG_MOVE_TRY_REPLACE_SLOT_1,
    BFG_MOVE_TRY_REPLACE_SLOT_2,
    BFG_MOVE_TRY_REPLACE_SLOT_3,
    BFG_MOVE_TRY_REPLACE_SLOT_4,
    BFG_MOVE_TRY_REPLACE_FAILED,
};

enum {
    BFG_FACILITY_MODE_DEFAULT, // Arena, Palace, Pike, Pyramid, Tower
    BFG_FACILITY_MODE_DOME, 
    BFG_FACILITY_MODE_FACTORY, 
    BFG_FACILITY_MODE_TENT,
};

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H
