#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H

enum {
    BFG_MOVE_SELECT_DEFAULT, 
    BFG_MOVE_SELECT_RANDOM
};

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_GENERATOR_H
