#ifndef GUARD_CONFIG_FRONTIER_H
#define GUARD_CONFIG_FRONTIER_H

// Allow Z-Moves to be used
#define BF_ALLOW_Z_MOVES TRUE

// Allow duplicate held items
#define BF_ALLOW_DUPLICATE_ITEMS FALSE 

// Allow duplicate species
#define BF_ALLOW_DUPLICATE_SPECIES FALSE 

// If this is set to true, lvl. 50 facilities will be level-scaled 
// down if above lvl. 50, instead of banning the Pokemon. If this
// is set to true, the below values will be referenced for if 
// Pokemon below that level should be scaled up, or left as-is.s
#define BF_ENABLE_LEVEL_SCALING TRUE

#define BF_BATTLE_FRONTIER_LEVEL_50_SCALE_UP TRUE // Scale pokemon below 'BATTLE_FRONTIER_LEVEL_50_SCALE_LEVEL' to that level in Level 50 Battle Frontier Facilities 
#define BF_BATTLE_FRONTIER_LEVEL_50_SCALE_LEVEL 50 // Scale Pokemon above (or below if set) this level to this level

#define BF_BATTLE_FRONTIER_LEVEL_50_ALLOW_BANNED_SPECIES FALSE // Allow typically banned species (i.e. mythicals, legends)
#define BF_BATTLE_FRONTIER_LEVEL_50_CUSTOM_BANNED_SPECIES TRUE // Use custom banned species list
#define BF_BATTLE_FRONTIER_LEVEL_50_CUSTOM_BANNED_SPECIES_LIST \
    SPECIES_MEWTWO, SPECIES_HO_OH, SPECIES_LUGIA, \
    SPECIES_KYOGRE, SPECIES_GROUDON, SPECIES_RAYQUAZA, SPECIES_DEOXYS, \
    SPECIES_DIALGA, SPECIES_PALKIA, SPECIES_GIRATINA, SPECIES_ARCEUS, \
    SPECIES_RESHIRAM, SPECIES_ZEKROM, SPECIES_KYUREM, \
    SPECIES_XERNEAS, SPECIES_YVELTAL, SPECIES_ZYGARDE, \
    SPECIES_COSMOG, SPECIES_COSMOEM, SPECIES_SOLGALEO, SPECIES_LUNALA, SPECIES_NECROZMA, \
    SPECIES_ZACIAN, SPECIES_ZAMAZENTA, SPECIES_ETERNATUS, SPECIES_CALYREX, \
    SPECIES_KORAIDON, SPECIES_MIRAIDON, SPECIES_TERAPAGOS

#define BF_BATTLE_FRONTIER_LEVEL_OPEN_SCALE_UP TRUE // Scale pokemon below 'BATTLE_FRONTIER_LEVEL_OPEN_SCALE_LEVEL' to that level in Open Level Battle Frontier Facilities 
#define BF_BATTLE_FRONTIER_LEVEL_OPEN_SCALE_LEVEL 50 // Scale Pokemon above (or below if set) this level to this level

#define BF_BATTLE_FRONTIER_LEVEL_OPEN_ALLOW_BANNED_SPECIES TRUE // Allow typically banned species (i.e. mythicals, legends)
#define BF_BATTLE_FRONTIER_LEVEL_OPEN_CUSTOM_BANNED_SPECIES TRUE // Use custom banned species list
#define BF_BATTLE_FRONTIER_LEVEL_OPEN_CUSTOM_BANNED_SPECIES_LIST \
    SPECIES_MEWTWO, SPECIES_HO_OH, SPECIES_LUGIA, \
    SPECIES_KYOGRE, SPECIES_GROUDON, SPECIES_RAYQUAZA, SPECIES_DEOXYS, \
    SPECIES_DIALGA, SPECIES_PALKIA, SPECIES_GIRATINA, SPECIES_ARCEUS, \
    SPECIES_RESHIRAM, SPECIES_ZEKROM, SPECIES_KYUREM, \
    SPECIES_XERNEAS, SPECIES_YVELTAL, SPECIES_ZYGARDE, \
    SPECIES_COSMOG, SPECIES_COSMOEM, SPECIES_SOLGALEO, SPECIES_LUNALA, SPECIES_NECROZMA, \
    SPECIES_ZACIAN, SPECIES_ZAMAZENTA, SPECIES_ETERNATUS, SPECIES_CALYREX, \
    SPECIES_KORAIDON, SPECIES_MIRAIDON, SPECIES_TERAPAGOS

#define BF_BATTLE_FRONTIER_LEVEL_TENT_SCALE_UP TRUE // Scale pokemon below 'BF_BATTLE_FRONTIER_LEVEL_TENT_SCALE_LEVEL' to that level in Battle Tent Facilities 
#define BF_BATTLE_FRONTIER_LEVEL_TENT_SCALE_LEVEL 30 // Scale Pokemon above (or below if set) this level to this level

#define BF_BATTLE_FRONTIER_LEVEL_TENT_ALLOW_BANNED_SPECIES FALSE // Allow typically banned species (i.e. mythicals, legends)
#define BF_BATTLE_FRONTIER_LEVEL_TENT_CUSTOM_BANNED_SPECIES FALSE // Use custom banned species list
#define BF_BATTLE_FRONTIER_LEVEL_TENT_CUSTOM_BANNED_SPECIES_LIST \
    SPECIES_MEWTWO, SPECIES_HO_OH, SPECIES_LUGIA, \
    SPECIES_KYOGRE, SPECIES_GROUDON, SPECIES_RAYQUAZA, SPECIES_DEOXYS, \
    SPECIES_DIALGA, SPECIES_PALKIA, SPECIES_GIRATINA, SPECIES_ARCEUS, \
    SPECIES_RESHIRAM, SPECIES_ZEKROM, SPECIES_KYUREM, \
    SPECIES_XERNEAS, SPECIES_YVELTAL, SPECIES_ZYGARDE, \
    SPECIES_COSMOG, SPECIES_COSMOEM, SPECIES_SOLGALEO, SPECIES_LUNALA, SPECIES_NECROZMA, \
    SPECIES_ZACIAN, SPECIES_ZAMAZENTA, SPECIES_ETERNATUS, SPECIES_CALYREX, \
    SPECIES_KORAIDON, SPECIES_MIRAIDON, SPECIES_TERAPAGOS

#endif // GUARD_CONFIG_FRONTIER_H
