Common_EventScript_Placeholder::
	lock
	faceplayer
	msgbox Common_EventScript_Placeholder_Text_0
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1
	release
	end


Common_EventScript_Placeholder_Text_0:
	.string "Hello! I'm a placeholder NPC!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0:
	.string "Welcome to the Battle Frontier\n"
	.string "Underground!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1:
	.string "You can find anything you need for\n"
	.string "battling here.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2:
	.string "This is the closest entrance for the\n"
	.string "Battle Dome facility.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3:
	.string "Feel free to use your bike!$"

BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Factory and Battle Pike\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Tower, Ranking Hall and BP\l"
	.string "Exchange Service facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Palace, POKéMON Center and\l"
	.string "POKéMART facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0:
	.string "This is the best entrance for the\n"
	.string "Battle Pyramid and Battle Arena\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0:
	.string "This is the entrance to the Battle\n"
	.string "Frontier Underground Pokémon Center.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1:
	.string "I hope you enjoy your stay!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0:
	.string "Have you been into the POKéMON Day\n"
	.string "Care yet?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1:
	.string "You can buy new training-ready\n"
	.string "POKéMON, or even breed your own!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2:
	.string "It's worth checking out if you are\n"
	.string "looking to add some new POKéMON to your\l"
	.string "team!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0:
	.string "Have you played the Open Level Rules at\n"
	.string "the Battle Frontier?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1:
	.string "You can use legendary POKéMON, even\n"
	.string "the most powerful ones!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2:
	.string "I've heard Xerneas and Groudon are a\n"
	.string "really powerful combo!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0:
	.string "I've been losing a lot of battles lately.$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1:
	.string "Maybe some stronger POKéMON would\n"
	.string "help?$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0:
	.string "The medicine at this shop is perfect\n"
	.string "for training Pokemon.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1:
	.string "You can use a BOTTLE CAP to max out all\n"
	.string "of your POKéMON's base stats, and other\l"
	.string "items such as HP UP, Zinc and Carbos to\l"
	.string "help your POKéMON reach their full\l"
	.string "potential!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0:
	.string "My WEAVILE had a calm nature, but I\n"
	.string "used a mint to change it to a jolly\l"
	.string "nature.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1:
	.string "It's much faster and stronger now!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_0:
	.string "If you want to make a simple ev spreads,\n"
	.string "all you need is 7 of two different types\l"
	.string "of ev training medicine, and one\l"
	.string "feather for the leftover stat.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_1:
	.string "If you want to make more complicated\n"
	.string "spreads, you might want to use a\l"
	.string "calculator!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_2:
	.string "You might find the following website\n"
	.string "useful!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_3:
	.string "www.dragapult.xyz/ebr-ev-spread-utility$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0:
	.string "Psst! I'll let you in a little secret!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1:
	.string "If you train your POKéMON with 252 EVs\n"
	.string "in two stats and then 4 points in\l"
	.string "another, you are missing out on two\l"
	.string "stat points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2:
	.string "If you use a spread with 4 EVs in 3\n"
	.string "stats, 244 in one, and then 252 in the\l"
	.string "other - You'll get an extra two stat\l"
	.string "points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3:
	.string "Don't share this with anyone else!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0:
	.string "Sometimes, it can be really hard to come\n"
	.string "up with a good EV spread.$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1:
	.string "However, there are programs out there\n"
	.string "that can help you!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2:
	.string "www.dragapult.xyz/coverage-calculator$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0:
	.string "Did you know? Sometimes, it's beneficial\n"
	.string "to have lower stats on your Pokemon!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1:
	.string "On special attackers, having a low\n"
	.string "attack stat can result in opposing Foul\l"
	.string "Plays doing less damage!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2:
	.string "Or on trick room POKéMON, having a low\n"
	.string "speed stat will make them faster under\l"
	.string "trick room!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3:
	.string "Keep these in mind when you are\n"
	.string "training your POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0:
	.string "If your POKéMON has a major type\n"
	.string "weakness holding it back, type resist\l"
	.string "berries may be the solution!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1:
	.string "These berries will halve the incoming\n"
	.string "damage of a single super-effective\l"
	.string "move of a given type.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2:
	.string "This includes double weaknesses!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0:
	.string "Status berries are great for saving\n"
	.string "your POKéMON in difficult situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1:
	.string "If you get randomly frozen, paralyzed\n"
	.string "or burnt, a Lum berry will restore the\l"
	.string "status of your POKéMON once!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2:
	.string "The berries for restoring a specific\n"
	.string "status are more niche, but are useful in\l"
	.string "certain situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0:
	.string "I love giving one of my POKéMON a Sitrus\n"
	.string "Berry, so they can recover a quarter of\l"
	.string "their health each battle!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1:
	.string "Other recovery berries such as Figy,\n"
	.string "Mago, etc. restore more health, but are\l"
	.string "trigged at lower health.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2:
	.string "Also, make sure you use the right berry\n"
	.string "for your POKéMON's nature, or they will\l"
	.string "be confused by it!$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_0:
	.string "Have you been into the POKéMON CENTRE\n"
	.string "yet? There are some interesting people\l"
	.string "in there!$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_1:
	.string "You can have your POKéMON's\n"
	.string "GIGANTAMAX factor changed, or even\l"
	.string "trade BATTLE POINTS for rare items!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0:
	.string "Have you been into the GAME CORNER\n"
	.string "yet?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1:
	.string "It's a fun change of pace from battling.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2:
	.string "Just don't bet more than you can afford\n"
	.string "to lose!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0:
	.string "Have you seen these vending machines\n"
	.string "around?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1:
	.string "You can use them to exchange BATTLE\n"
	.string "POINTS for money, and vice versa.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2:
	.string "Similarly, you can use the machines in\n"
	.string "the back left of the GAME CORNER to\l"
	.string "exchange coins for money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0:
	.string "If you're running low on cash, use the\n"
	.string "machine here to convert BATTLE POINTS\l"
	.string "into money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1:
	.string "If you need to earn some BP and don't\n"
	.string "have a team yet, try your luck at the\l"
	.string "BATTLE FACTORY!$"
