Common_EventScript_Placeholder::
	lock
	faceplayer
	msgbox Common_EventScript_Placeholder_Text_0
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_3
	msgbox BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_4
	release
	end


BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_3
	msgbox BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_4
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_BattleSpotEntrance_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleSpotEntrance_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_BattleSpotEntrance_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_2
	msgbox BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_3
	release
	end


BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_MoveRelearner_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_MoveRelearner_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_MoveRelearner_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_MoveTutor_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_MoveTutor_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_MoveTutor_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B1F_EventScript_NewKeyItem_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B1F_EventScript_NewKeyItem_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B1F_EventScript_NewKeyItem_Visitor1_Text_1
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_1
	msgbox BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_2
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_1
	release
	end


BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_1
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_2
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_3
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_4
	release
	end


BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder2_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder2_Text_1
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_3
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_4
	release
	end


BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_1
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_2
	release
	end


BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor2::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor2_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor2_Text_1
	release
	end


BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3::
	lock
	faceplayer
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_0
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_1
	msgbox BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_2
	release
	end


Common_EventScript_Placeholder_Text_0:
	.string "Hello! I'm a placeholder NPC!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_0:
	.string "Welcome to the Battle Frontier\n"
	.string "Underground!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_1:
	.string "You can find anything you need for\n"
	.string "battling here.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_2:
	.string "This is the closest entrance for the\n"
	.string "Battle Dome facility.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeGreeter_Text_3:
	.string "Feel free to use your bike!$"

BattleFrontier_Underground_B1F_EventScript_BattlePikeGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Factory and Battle Pike\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattleTowerGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Tower, Ranking Hall and BP\l"
	.string "Exchange Service facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePalaceGreeter_Text_0:
	.string "This is the closest entrance for the\n"
	.string "Battle Palace, POKéMON Center and\l"
	.string "POKéMART facilities.$"

BattleFrontier_Underground_B1F_EventScript_BattlePyramidGreeter_Text_0:
	.string "This is the best entrance for the\n"
	.string "Battle Pyramid and Battle Arena\l"
	.string "facilities.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_0:
	.string "This is the entrance to the Battle\n"
	.string "Frontier Underground Pokémon Center.$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenterGreeter_Text_1:
	.string "I hope you enjoy your stay!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_0:
	.string "Have you been into the POKéMON Day\n"
	.string "Care yet?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_1:
	.string "You can buy new training-ready\n"
	.string "POKéMON, or even breed your own!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor1_Text_2:
	.string "It's worth checking out if you are\n"
	.string "looking to add some new POKéMON to your\l"
	.string "team!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_0:
	.string "Have you played the Open Level Rules at\n"
	.string "the Battle Frontier?$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_1:
	.string "You can use legendary POKéMON, even\n"
	.string "the most powerful ones!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor2_Text_2:
	.string "I've heard Xerneas and Groudon are a\n"
	.string "really powerful combo!$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_0:
	.string "I've sure been losing a lot of battles\n"
	.string "lately ...$"

BattleFrontier_Underground_B1F_EventScript_LegendaryShop_Visitor3_Text_1:
	.string "Maybe some stronger POKéMON would\n"
	.string "help?$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_0:
	.string "The medicine at this shop is perfect\n"
	.string "for training POKéMON.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor1_Text_1:
	.string "You can use a BOTTLE CAP to max out all\n"
	.string "of your POKéMON's base stats, and other\l"
	.string "items such as HP UP, Zinc and Carbos to\l"
	.string "help your POKéMON reach their full\l"
	.string "potential!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_0:
	.string "My WEAVILE had a calm nature, but I\n"
	.string "used a mint to change it to a jolly\l"
	.string "nature.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor2_Text_1:
	.string "It's much faster and stronger now!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_0:
	.string "If you want to make a simple ev spreads,\n"
	.string "all you need is 7 of two different types\l"
	.string "of ev training medicine, and one\l"
	.string "feather for the leftover stat.$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_1:
	.string "If you want to make more complicated\n"
	.string "spreads, you might want to use a\l"
	.string "calculator!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_2:
	.string "You might find this website useful!$"

BattleFrontier_Underground_B1F_EventScript_ChemistShop_Visitor3_Text_3:
	.string "www.dragapult.xyz/ebr-ev-spread-utility$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_0:
	.string "Have you entered a DYNAMAX BATTLE\n"
	.string "yet?$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_1:
	.string "Simply turn on your DYNAMAX BAND from\n"
	.string "the KEY ITEMS menu, and you can use it\l"
	.string "in the Frontier!$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_2:
	.string "If you don't have a DYNAMAX BAND\n"
	.string "already, you can buy one from the KEY\l"
	.string "ITEM shop at the bottom-right side of\l"
	.string "the mall.$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_3:
	.string "Keep in mind, though - You won't be able\n"
	.string "to use Tera, Mega Evolution or Z-Moves\l"
	.string "while it is active.$"

BattleFrontier_Underground_B1F_EventScript_OtherShop_Visitor1_Text_4:
	.string "Make sure to max out your POKéMON's\n"
	.string "dynamax level using MAX MUSHROOMS\l"
	.string "first!$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_0:
	.string "Have you heard of Terastalisation?$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_1:
	.string "It allows one of your POKéMON to change\n"
	.string "into a different type once per game!$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_2:
	.string "If you don't have a Tera Orb already,\n"
	.string "you can buy one from the KEY ITEM shop\l"
	.string "at the bottom-right side of the mall.$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_3:
	.string "The type changes depending on the\n"
	.string "POKéMON's Tera Type - Which can be\l"
	.string "changed using Tera Shards.$"

BattleFrontier_Underground_B1F_EventScript_TeraShop_Visitor1_Text_4:
	.string "You can check the Tera Type of your\n"
	.string "POKéMON from the summary menu!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_0:
	.string "Psst! I'll let you in a little secret!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_1:
	.string "If you train your POKéMON with 252 EVs\n"
	.string "in two stats and then 4 points in\l"
	.string "another, you are missing out on two\l"
	.string "stat points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_2:
	.string "If you use a spread with 4 EVs in 3\n"
	.string "stats, 244 in one, and then 252 in the\l"
	.string "other - You'll get an extra two stat\l"
	.string "points!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor1_Text_3:
	.string "Don't share this with anyone else!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_0:
	.string "Sometimes, it can be really hard to come\n"
	.string "up with a good EV spread.$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_1:
	.string "However, there are programs out there\n"
	.string "that can help you!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_2:
	.string "You might find the this website useful!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor2_Text_3:
	.string "www.dragapult.xyz/coverage-calculator$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_0:
	.string "Did you know? Sometimes, it's beneficial\n"
	.string "to have lower stats on your POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_1:
	.string "On special attackers, having a low\n"
	.string "attack stat can result in opposing Foul\l"
	.string "Plays doing less damage!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_2:
	.string "Or on trick room POKéMON, having a low\n"
	.string "speed stat will make them faster under\l"
	.string "trick room!$"

BattleFrontier_Underground_B1F_EventScript_TrainingShop_Visitor3_Text_3:
	.string "Keep these in mind when you are\n"
	.string "training your POKéMON!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_0:
	.string "If your POKéMON has a major type\n"
	.string "weakness holding it back, type resist\l"
	.string "berries may be the solution!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_1:
	.string "These berries will halve the incoming\n"
	.string "damage of a single super-effective\l"
	.string "move of a given type.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor1_Text_2:
	.string "This includes double weaknesses!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_0:
	.string "Status berries are great for saving\n"
	.string "your POKéMON in difficult situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_1:
	.string "If you get randomly frozen, paralyzed\n"
	.string "or burnt, a Lum berry will restore the\l"
	.string "status of your POKéMON once!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor2_Text_2:
	.string "The berries for restoring a specific\n"
	.string "status are more niche, but are useful in\l"
	.string "certain situations.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_0:
	.string "I like to give one of my POKéMON a\n"
	.string "Sitrus Berry, so they can recover a\l"
	.string "quarter of their health each battle!$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_1:
	.string "Other recovery berries such as Figy,\n"
	.string "Mago, etc. restore more health, but are\l"
	.string "trigged at lower health.$"

BattleFrontier_Underground_B1F_EventScript_BerryShop_Visitor3_Text_2:
	.string "Also, make sure you use the right berry\n"
	.string "for your POKéMON's nature, or they will\l"
	.string "be confused by it!$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_0:
	.string "Have you been into the POKéMON CENTRE\n"
	.string "yet? There are some interesting people\l"
	.string "in there!$"

BattleFrontier_Underground_B1F_EventScript_PokemonCenter_Visitor1_Text_1:
	.string "You can have your POKéMON's\n"
	.string "GIGANTAMAX factor changed, or even\l"
	.string "trade BATTLE POINTS for rare items!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_0:
	.string "Have you been into the GAME CORNER\n"
	.string "yet?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_1:
	.string "It's a fun change of pace from battling.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor1_Text_2:
	.string "Just don't bet more than you can afford\n"
	.string "to lose!$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_0:
	.string "Have you seen these vending machines\n"
	.string "around?$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_1:
	.string "You can use them to exchange BATTLE\n"
	.string "POINTS for money, and vice versa.$"

BattleFrontier_Underground_B1F_EventScript_GameCorner_Visitor2_Text_2:
	.string "Similarly, you can use the machines in\n"
	.string "the back left of the GAME CORNER to\l"
	.string "exchange coins for money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_0:
	.string "You see that vending machine over\n"
	.string "there? You can use that to convert\l"
	.string "BATTLE POINTS to money!$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_1:
	.string "You can't buy anything down here with\n"
	.string "BP, so you'll need to convert it first.$"

BattleFrontier_Underground_B1F_EventScript_BattleDomeEntrance_Visitor1_Text_2:
	.string "If you don't have a team yet, maybe try\n"
	.string "your luck at the BATTLE FACTORY?$"

BattleFrontier_Underground_B1F_EventScript_BattleSpotEntrance_Visitor1_Text_0:
	.string "Just downstairs from here is the Battle\n"
	.string "Spot - The new battle facility\l"
	.string "currently under construction.$"

BattleFrontier_Underground_B1F_EventScript_BattleSpotEntrance_Visitor1_Text_1:
	.string "You can't battle yet, but you can\n"
	.string "already buy pre-trained POKéMON and\l"
	.string "teams - be sure to check it out!$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_0:
	.string "Gems are great! They boost the power of\n"
	.string "a POKéMON's move of the same type once\l"
	.string "by 30%, but are only used if the move\l"
	.string "connects!$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_1:
	.string "Think of it like a Z-Move, but you can\n"
	.string "use multiple per match, and doesn't go\l"
	.string "through protect.$"

BattleFrontier_Underground_B1F_EventScript_GemShop_Visitor1_Text_2:
	.string "Definitely think about using them!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_0:
	.string "Type-Boosting items are great! They\n"
	.string "boost the power of a POKéMON's move\l"
	.string "move of the same type every turn by\l"
	.string "20%!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_1:
	.string "They work great for POKéMON who mainly\n"
	.string "focus on a single attacking type!$"

BattleFrontier_Underground_B1F_EventScript_TypeItem_Visitor1_Text_2:
	.string "You should consider using them!$"

BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_0:
	.string "There are lots of POKéMON that can use\n"
	.string "common items, but sometimes a less\l"
	.string "common item allows a POKéMON to really\l"
	.string "shine.$"

BattleFrontier_Underground_B1F_EventScript_UncommonItem_Visitor1_Text_1:
	.string "If you are struggling to pick an item,\n"
	.string "definitely take a look!$"

BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_0:
	.string "Some items are so powerful, they stand\n"
	.string "in a class of their own - Almost any\l"
	.string "POKéMON can benefit from them!$"

BattleFrontier_Underground_B1F_EventScript_CommonItem_Visitor1_Text_1:
	.string "Whenever I'm looking for an item for a\n"
	.string "new POKéMON, this is the first place I\l"
	.string "look.$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_0:
	.string "Z-Crystals are incredible - There is one\n"
	.string "for every type, and some POKéMON even\l"
	.string "have unique Z-Moves!$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_1:
	.string "Be careful, though - If you use one into\n"
	.string "an immunity, it'll be wasted - and it only\l"
	.string "deals 1/4 through protect!$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_2:
	.string "If you don't have a Z-Ring already, you\n"
	.string "can buy one from the KEY ITEM shop at\l"
	.string "the bottom-right side of the mall.$"

BattleFrontier_Underground_B1F_EventScript_ZCrystal_Visitor1_Text_3:
	.string "Isn't the risk-reward balance\n"
	.string "thrilling?$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_0:
	.string "Mega evolution POKéMON are incredibly\n"
	.string "strong - But you can only use one per\l"
	.string "battle!$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_1:
	.string "Some megas best used with a team built\n"
	.string "around them, and others work well to\l"
	.string "support a team.$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_2:
	.string "If you don't have a Mega Stone already,\n"
	.string "you can buy one from the KEY ITEM shop\l"
	.string "at the bottom-right side of the mall.$"

BattleFrontier_Underground_B1F_EventScript_MegaStone_Visitor1_Text_3:
	.string "Hmmm ... Which one do I pick this time?$"

BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_0:
	.string "Wow, they have the complete set of TMs\n"
	.string "and HMs here!$"

BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_1:
	.string "I found a few while exploring, but I'll\n"
	.string "have to buy the rest when I need them.$"

BattleFrontier_Underground_B1F_EventScript_TMHMShop_Visitor1_Text_2:
	.string "Just remember, you won't be able to pick\n"
	.string "them up if you find them later!$"

BattleFrontier_Underground_B1F_EventScript_MoveRelearner_Visitor1_Text_0:
	.string "I just finished training up my\n"
	.string "WHIMSICOTT - And it's only Level 1!$"

BattleFrontier_Underground_B1F_EventScript_MoveRelearner_Visitor1_Text_1:
	.string "Any level-up moves it needed, I could\n"
	.string "teach them to it right here!$"

BattleFrontier_Underground_B1F_EventScript_MoveTutor_Visitor1_Text_0:
	.string "I just taught my INCINEROAR FAKE OUT -\n"
	.string "a move it can normally only learn\l"
	.string "through breeding!$"

BattleFrontier_Underground_B1F_EventScript_MoveTutor_Visitor1_Text_1:
	.string "I'll definitely have to come back here\n"
	.string "with my RILLABOOM later!$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_0:
	.string "Did you know? You can swap a POKéMON's\n"
	.string "POKéBALL by simply using the ball you\l"
	.string "want on them from your bag!$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_1:
	.string "You'll even get back the ball it was\n"
	.string "originally captured in, too.$"

BattleFrontier_Underground_B1F_EventScript_PokeBall_Visitor1_Text_2:
	.string "Try it out for yourself!$"

BattleFrontier_Underground_B1F_EventScript_NewKeyItem_Visitor1_Text_0:
	.string "Wow, this place has so many unique items\n"
	.string "- and you only need to buy them once!$"

BattleFrontier_Underground_B1F_EventScript_NewKeyItem_Visitor1_Text_1:
	.string "Which one will you be picking up first?$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_0:
	.string "If you want to try a new style of\n"
	.string "battling, maybe look at changing the\l"
	.string "battle ban lists, or even trying a new\l"
	.string "ruleset!$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_1:
	.string "You can even play against the old\n"
	.string "battle frontier sets if you'd like, too.$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor1_Text_2:
	.string "The possibilities are endless!$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_0:
	.string "How do you feel about dynamax battles?$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_1:
	.string "Some people prefer them over normal\n"
	.string "battles.$"

BattleFrontier_Underground_B2F_PokeCenter_1F_EventScript_Visitor2_Text_2:
	.string "Me? I just like the cool Gigantamax\n"
	.string "formes!$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_0:
	.string "Have you ever played in a tournament\n"
	.string "before?$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_1:
	.string "I've heard they hold them in a place far\n"
	.string "away from here.$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor1_Text_2:
	.string "You can even qualify for the world\n"
	.string "championships!$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_0:
	.string "I've won lots of games at the Battle\n"
	.string "Frontier, but I'm not sure I'm ready for\l"
	.string "union room battles just yet ...$"

BattleFrontier_Underground_B2F_PokeCenter_2F_EventScript_Visitor2_Text_1:
	.string "I guess the only way to find out is to\n"
	.string "try!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_0:
	.string "Welcome to the Battle Spot!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_1:
	.string "This is the door for the rating battles\n"
	.string "facility.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_2:
	.string "Start from the 1500s, and rise to the\n"
	.string "top of the 2000s!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_3:
	.string "At the moment, this facility is closed\n"
	.string "for development.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder1_Text_4:
	.string "Please come back soon!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder2_Text_0:
	.string "This is the door for the ranked battles\n"
	.string "facility.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Placeholder2_Text_1:
	.string "Rise through the ranks to the top of\n"
	.string "the Master Ball Tier!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_0:
	.string "Have you had a look at the sample teams\n"
	.string "shop yet?$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_1:
	.string "It's a great way to get started if you\n"
	.string "aren't sure what to use!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor1_Text_2:
	.string "I hope they add some single battle\n"
	.string "teams soon, though.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor2_Text_0:
	.string "The sample sets shop is really useful if\n"
	.string "you want to try some new Pokemon, but\l"
	.string "aren't sure how to train them.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor2_Text_1:
	.string "It's a great way to save time when\n"
	.string "experimenting or building a new team!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_0:
	.string "From what I've heard, battles in this\n"
	.string "facility will be filled with challenging\l"
	.string "opponents!$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_1:
	.string "Progress will be based on your win-loss\n"
	.string "rating rather than relying on win\l"
	.string "streaks only.$"

BattleFrontier_Underground_B2F_BattleSpot_1F_EventScript_Visitor3_Text_2:
	.string "I'm so excited for it to open!$"
