// File Auto-Generated By tools/bfg_helpers/battle_spot.py

// doubles - standard
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_COUNT 4

#define BATTLE_SPOT_MON_DOUBLES_STANDARD_GARDEVOIR 0
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN 1
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_HEATRAN 2
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS 3

const struct TrainerMon gBattleSpotMonsDoublesStandard[BATTLE_SPOT_MON_DOUBLES_STANDARD_COUNT] = {
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_GARDEVOIR] = {
        .species = SPECIES_GARDEVOIR,
        .moves = {
            MOVE_PROTECT,
            MOVE_HYPER_VOICE,
            MOVE_TRICK_ROOM,
            MOVE_PSYCHIC,
        },
        .heldItem = ITEM_GARDEVOIRITE,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(244, 0, 196, 36, 4, 28),
        .nature = NATURE_MODEST
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN] = {
        .species = SPECIES_LANDORUS_THERIAN,
        .moves = {
            MOVE_U_TURN,
            MOVE_STOMPING_TANTRUM,
            MOVE_EARTHQUAKE,
            MOVE_ROCK_SLIDE,
        },
        .heldItem = ITEM_CHOICE_SCARF,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(4, 196, 4, 0, 52, 252),
        .nature = NATURE_ADAMANT
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_HEATRAN] = {
        .species = SPECIES_HEATRAN,
        .moves = {
            MOVE_PROTECT,
            MOVE_SUBSTITUTE,
            MOVE_HEAT_WAVE,
            MOVE_EARTH_POWER,
        },
        .heldItem = ITEM_SHUCA_BERRY,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(228, 0, 4, 236, 4, 36),
        .nature = NATURE_MODEST
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS] = {
        .species = SPECIES_IRON_HANDS,
        .moves = {
            MOVE_DRAIN_PUNCH,
            MOVE_WILD_CHARGE,
            MOVE_HEAVY_SLAM,
            MOVE_FAKE_OUT,
        },
        .heldItem = ITEM_ASSAULT_VEST,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(60, 156, 36, 0, 252, 4),
        .nature = NATURE_ADAMANT
    },
};