// File Auto-Generated By tools/bfg_helpers/battle_spot.py

// doubles - standard
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_COUNT 8

#define BATTLE_SPOT_MON_DOUBLES_STANDARD_GARDEVOIR 0
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN 1
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_HEATRAN 2
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS 3
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_CHARIZARD 4
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN_2 5
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_FLUTTER_MANE 6
#define BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS_2 7

const struct TrainerMon gBattleSpotMonsDoublesStandard[BATTLE_SPOT_MON_DOUBLES_STANDARD_COUNT] = {
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_GARDEVOIR] = {
        .species = SPECIES_GARDEVOIR,
        .moves = {
            MOVE_PROTECT,
            MOVE_HYPER_VOICE,
            MOVE_TRICK_ROOM,
            MOVE_PSYCHIC,
        },
        .heldItem = ITEM_GARDEVOIRITE,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(244, 0, 196, 28, 36, 4),
        .friendship = 255,
        .nature = NATURE_MODEST,
        .gender = GENDER_FEMALE,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN] = {
        .species = SPECIES_LANDORUS_THERIAN,
        .moves = {
            MOVE_U_TURN,
            MOVE_STOMPING_TANTRUM,
            MOVE_EARTHQUAKE,
            MOVE_ROCK_SLIDE,
        },
        .heldItem = ITEM_CHOICE_SCARF,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(4, 196, 4, 252, 0, 52),
        .friendship = 255,
        .nature = NATURE_ADAMANT,
        .gender = GENDER_MALE,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_HEATRAN] = {
        .species = SPECIES_HEATRAN,
        .moves = {
            MOVE_PROTECT,
            MOVE_SUBSTITUTE,
            MOVE_HEAT_WAVE,
            MOVE_EARTH_POWER,
        },
        .heldItem = ITEM_SHUCA_BERRY,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(228, 0, 4, 36, 236, 4),
        .friendship = 255,
        .nature = NATURE_MODEST,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS] = {
        .species = SPECIES_IRON_HANDS,
        .moves = {
            MOVE_DRAIN_PUNCH,
            MOVE_WILD_CHARGE,
            MOVE_HEAVY_SLAM,
            MOVE_FAKE_OUT,
        },
        .heldItem = ITEM_ASSAULT_VEST,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(60, 156, 36, 4, 0, 252),
        .friendship = 255,
        .nature = NATURE_ADAMANT,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_CHARIZARD] = {
        .species = SPECIES_CHARIZARD,
        .moves = {
            MOVE_PROTECT,
            MOVE_SCORCHING_SANDS,
            MOVE_FLAMETHROWER,
            MOVE_SOLAR_BEAM,
        },
        .heldItem = ITEM_CHARIZARDITE_Y,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(204, 0, 108, 188, 4, 4),
        .friendship = 255,
        .nature = NATURE_MODEST,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_LANDORUS_THERIAN_2] = {
        .species = SPECIES_LANDORUS_THERIAN,
        .moves = {
            MOVE_U_TURN,
            MOVE_STOMPING_TANTRUM,
            MOVE_EARTHQUAKE,
            MOVE_ROCK_SLIDE,
        },
        .heldItem = ITEM_CHOICE_SCARF,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(4, 196, 4, 252, 0, 52),
        .friendship = 255,
        .nature = NATURE_ADAMANT,
        .gender = GENDER_MALE,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_FLUTTER_MANE] = {
        .species = SPECIES_FLUTTER_MANE,
        .moves = {
            MOVE_PROTECT,
            MOVE_DAZZLING_GLEAM,
            MOVE_SHADOW_BALL,
            MOVE_MOONBLAST,
        },
        .heldItem = ITEM_FAIRIUM_Z,
        .iv = TRAINER_PARTY_IVS(31, 0, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(140, 0, 188, 140, 36, 4),
        .friendship = 255,
        .nature = NATURE_MODEST,
        .dynamaxLevel = 10,
    },
    [BATTLE_SPOT_MON_DOUBLES_STANDARD_IRON_HANDS_2] = {
        .species = SPECIES_IRON_HANDS,
        .moves = {
            MOVE_DRAIN_PUNCH,
            MOVE_WILD_CHARGE,
            MOVE_HEAVY_SLAM,
            MOVE_FAKE_OUT,
        },
        .heldItem = ITEM_ASSAULT_VEST,
        .iv = TRAINER_PARTY_IVS(31, 31, 31, 31, 31, 31),
        .ev = TRAINER_PARTY_EVS(60, 156, 36, 4, 0, 252),
        .friendship = 255,
        .nature = NATURE_ADAMANT,
        .dynamaxLevel = 10,
    },
};