// File Auto-Generated By tools/bfg_helpers/battle_spot.py

// doubles - standard
#define BATTLE_SPOT_TRAINER_DOUBLES_STANDARD_COUNT 1

#define BATTLE_SPOT_TRAINER_DOUBLES_STANDARD_DAMON 0

const struct BattleSpotTrainer gBattleSpotTrainersDoublesStandard[BATTLE_SPOT_TRAINER_DOUBLES_STANDARD_COUNT] = {
    [BATTLE_SPOT_TRAINER_DOUBLES_STANDARD_DAMON] = {
        .trainer = {
            .facilityClass = FACILITY_CLASS_BRENDAN,
            .trainerName = _("DAMON"),
            .speechBefore = {EC_WORD_I_AM, EC_WORD_NEVER, EC_WORD_GOING, EC_WORD_TO, EC_WORD_LOSE, EC_WORD_EXCL},
            .speechWin = {EC_WORD_I_AM, EC_WORD_STRONG, EC_WORD_AREN_T, EC_WORD_I, EC_WORD_QUES, EC_EMPTY_WORD},
            .speechLose = {EC_WORD_WHAT, EC_WORD_QUES, EC_EMPTY_WORD, EC_WORD_BUT, EC_WORD_HOW, EC_WORD_QUES},
        },
        .tier = TIER_MASTER_BALL,
        .rating = 1843,
    },
};